--- 
blank_issues_enabled: false
contact_links: 
  - name: "Rocky Linux Community Support - Testing Team"
    url: "https://chat.rockylinux.org/rocky-linux/channels/testing"
    about: "Please ask and answer questions about openQA for Rocky Linux here.
